Add GitHub Actions workflow with echo steps

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,1 +1,22 @@
-# This is a basic workflow to help you get started with Actions
+---
+name: 01 - Building Blocks
+
+on:
+  workflow_dispatch:
+
+jobs:
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Say Hello
+        run: echo "Hello, World!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed Step
+        run: |
+          echo "I will fail now"
+          exit 1
+      - name: Say Goodbye
+        run: |
+          echo "This step will be skipped if the previous step fails"
